title: Tamalin
email: quytelda@tamalin.org
description: >-
  Information about me (Quytelda Kahja), my work, projects, and hobbies.
baseurl: "/"
url: "https://tamalin.org"
github_username: quytelda

# Server Well-Known directory.
include: [".well-known"]

# Build settings
remote_theme: quytelda/jekyll-theme-kernel

# Theme settings
logo: /assets/images/avatar.png
author: Quytelda Kahja
